name: myenv
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip=22.2.2
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pip:
    - blendmodes
    - accelerate
    - basicsr
    - fonts
    - font-roboto
    - gfpgan
    - gradio==3.23
    - invisible-watermark
    - omegaconf
    - opencv-contrib-python
    - requests
    - piexif
    - Pillow
    - pytorch_lightning==1.7.7
    - realesrgan
    - scikit-image>=0.19
    - timm==0.4.12
    - transformers==4.25.1
    - torch
    - einops
    - jsonmerge
    - clean-fid
    - resize-right
    - torchdiffeq
    - kornia
    - lark
    - inflection
    - GitPython
    - torchsde
    - safetensors
    - psutil
    - rich
